from tkinter import *
import pymysql.cursors
m=Tk()
m.geometry("400x200")
def bt():
    def dbbt():
        def dbt():
            db=pymysql.connect(host="localhost",user="root",password="tiger",database="myth")
            cur=db.cursor()
            cur.execute(f"insert into ticket(user_id,airline_id) values({ui.get()},{ai.get()})")
            db.commit()
            cur.execute(f"select t_id from ticket where airline_id={ai.get()} and user_id={ui.get()} ")
            out=cur.fetchall()
            Label(x,text={out}).place(x=40,y=220)
            Label(x,text="This is your ticket id.Do remember!").place(x=40,y=260)
            db.close()
        x=Tk()
        x.geometry("800x600")
        Label(x,text="choose an airline!").place(x=20,y=20)
        db=pymysql.connect(host="localhost",user="root",password="tiger",database="myth")
        cur=db.cursor()
        cur.execute(f"select * from plane where airline_from='{fr.get()}' and airline_to='{to.get()}' and airline_date='{td.get()}'")
        out=cur.fetchall()
        Label(x,text={out}).place(x=20,y=50)
        Label(x,text="These are the possible options.second last column-price  Last column-airline id").place(x=40,y=80)
        Label(x,text="Airline ID:").place(x=40,y=130)
        ai=Entry(x)
        ai.place(x=150,y=130)
        Button(x,text="Book",command=dbt).place(x=120,y=180)
        db.close()        
    u=Tk()
    u.geometry("400x600")
    Label(u,text="Enter Journey Details!").place(x=20,y=20)
    Label(u,text="User ID:").place(x=40,y=50)
    ui=Entry(u)
    ui.place(x=150,y=50)
    Label(u,text="From:").place(x=40,y=80)
    fr=Entry(u)
    fr.place(x=150,y=80)
    Label(u,text="To:").place(x=40,y=110)
    to=Entry(u)
    to.place(x=150,y=110)
    Label(u,text="Travel date:").place(x=40,y=140)
    td=Entry(u)
    td.place(x=150,y=140)
    Button(u,text="Done",command=dbbt).place(x=120,y=180)
def ct():
    def dbct():
        db=pymysql.connect(host="localhost",user="root",password="tiger",database="myth")
        cur=db.cursor()
        cur.execute(f"delete from ticket where t_id={ti.get()}")
        db.commit()
        db.close()
    u=Tk()
    u.geometry("400x600")
    Label(u,text="Cancelling? Think Again!").place(x=20,y=20)
    Label(u,text="Ticket ID:").place(x=40,y=70)
    ti=Entry(u)
    ti.place(x=150,y=70)
    Button(u,text="Done",command=dbct).place(x=90,y=120)
def aa():
    def dbaa():
        db=pymysql.connect(host="localhost",user="root",password="tiger",database="myth")
        cur=db.cursor()
        cur.execute(f"insert into plane(iata_code,airline_name,airline_from,airline_to,airline_date,cost)  values({ic.get()},'{an.get()}','{fr.get()}','{to.get()}','{td.get()}',{co.get()})")
        db.commit()
        cur.execute(f"select airline_id from plane where iata_code={ic.get()} and airline_name='{an.get()}' and airline_from='{fr.get()}' and airline_to='{to.get()}' and airline_date='{td.get()}' and cost={co.get()}")
        out=cur.fetchall()
        Label(u,text={out}).place(x=40,y=280)
        Label(u,text="Note: Remember this ID - Useful to remove airline").place(x=40,y=360)    
        db.close()
    u=Tk()
    u.geometry("400x600")
    Label(u,text="Enter Airline Details!").place(x=20,y=20)
    Label(u,text="Iata code:").place(x=40,y=50)
    ic=Entry(u)
    ic.place(x=150,y=50)
    Label(u,text="Airline Name:").place(x=40,y=80)
    an=Entry(u)
    an.place(x=150,y=80)
    Label(u,text="From:").place(x=40,y=110)
    fr=Entry(u)
    fr.place(x=150,y=110)
    Label(u,text="To:").place(x=40,y=140)
    to=Entry(u)
    to.place(x=150,y=140)
    Label(u,text="Travel Date:").place(x=40,y=170)
    td=Entry(u)
    td.place(x=150,y=170)
    Label(u,text="cost:").place(x=40,y=200)
    co=Entry(u)
    co.place(x=150,y=200)
    Button(u,text="Done",command=dbaa).place(x=120,y=250)
def ra():
    def dbra():
        db=pymysql.connect(host="localhost",user="root",password="tiger",database="myth")
        cur=db.cursor()
        cur.execute(f"delete from plane where airline_id={ai.get()}")
        db.commit()
        db.close()
    u=Tk()
    u.geometry("400x600")
    Label(u,text="Organisational Issues! Let us Know!").place(x=20,y=20)
    Label(u,text="Airline ID:").place(x=40,y=50)
    ai=Entry(u)
    ai.place(x=150,y=50)
    Button(u,text="Done",command=dbra).place(x=90,y=80)
def admin():
    u=Tk()
    u.geometry("400x400")
    Label(u,text="Choose an Action!").place(x=20,y=20)
    Button(u,text="Add Airline",command=aa).place(x=40,y=50)
    Button(u,text="Remove Airline",command=ra).place(x=40,y=80)
def pd():
    def dbpd():
        db=pymysql.connect(host="localhost",user="root",password="tiger",database="myth")
        cur=db.cursor()
        cur.execute(f"insert into user(user_name,user_dob,user_phone) values('{un.get()}','{ud.get()}',{up.get()})")
        db.commit()
        cur.execute(f"select user_id from user where user_name='{un.get()}' and user_dob='{ud.get()}' and user_phone={up.get()}")
        out=cur.fetchall()
        Label(u,text={out}).place(x=40,y=330)
        Label(u,text="Note:This will be your User ID.").place(x=40,y=360)
    u=Tk()
    u.geometry("400x600")
    Label(u,text="Enter Personal Details!").place(x=20,y=20)
    Label(u,text="User Name:").place(x=40,y=80)
    un=Entry(u)
    un.place(x=150,y=80)
    Label(u,text="DOB:").place(x=40,y=110)
    ud=Entry(u)
    ud.place(x=150,y=110)
    Label(u,text="Contact number:").place(x=40,y=140)
    up=Entry(u)
    up.place(x=150,y=140)
    Button(u,text="Done",command=dbpd).place(x=120,y=300)
def zen():
    u=Tk()
    u.geometry("400x400")
    Label(u,text="Choose an Action").place(x=20,y=20)
    Button(u,text="Book Ticket",command=bt).place(x=40,y=50)
    Button(u,text="Cancel ticket",command=ct).place(x=40,y=80)
def user():
    u=Tk()
    u.geometry("400x400")
    Label(u,text="Have u registered with us?").place(x=20,y=20)
    Button(u,text="New User",command=pd).place(x=40,y=50)
    Button(u,text="Registered User",command=zen).place(x=40,y=80)
    
Label(m,text="Welcome To Airline Management System!").place(x=20,y=20)
Button(m,text="User",command=user).place(x=60,y=70)
Button(m,text="Admin",command=admin).place(x=60,y=100)
m.mainloop()